### ISSUE TITLE
Add Project Info/Didactic Text to mftm-frontend

### ISSUE THREAD

**Issue by brannondorsey** [brangerbriz/messages-from-the-mines#4]
Have some kind of about page on the frontend so that users can learn about the project/understand what they are looking at. It would be nice to also have UI help/explanation here too.

**Comment by nbriz** [comment]
- replace valid toggle button w/info text button ( to pull this page back up )
- add page min size warning logic here ( instead of alert() )
- add nsfw toggle here ( instead of in hidden menu )
- add "this is beta" message/warning + contact info / issues page
